graph:
  tweetstream:
    class: TwitterStream
    config:
      consumer_key: $TWITTER_CONSUMER_KEY
      consumer_secret: $TWITTER_CONSUMER_SECRET
      access_token: $TWITTER_ACCESS_TOKEN
      access_token_secret: $TWITTER_ACCESS_TOKEN_SECRET
      filter_retweets: True
      track:
        - '#brexit'

  cleanup:
    input: tweetstream
    class: TweetCleaner
    config:
      remove_usernames: True
      remove_urls: True
      split_hashtags: True

  sentiment_analyser:
    input: cleanup
    class: VaderAnalyzer

  pprint:
    input: sentiment_analyser
    class: PrettyPrinter
    config:
      pos: 0.05
      neg: -0.05

logging:
  level: WARNING