graph:
  twitter:
    config:
      consumer_key:
      consumer_secret:
      access_token:
      access_token_secret:
      track:
        - brexit
  filter:
    _input: twitter
  textblob:
    config:
      analyzer: PatternAnalyzer
    _input: filter
  pprint:
    _input: textblob
logging:
  level: WARNING